### ISSUE TITLE
I already have images/box art, but am missing any text - it would be nice to choose what to scrape for

### ISSUE THREAD

**Issue by cb109** [milouk/artie#20]
Current workaround is to backup box art, scrape, then unzip backup to use the prior images. It would be nice to be able to select beforehand though.

Thanks for creating and sharing this software!

**Comment by Giuleus957** [comment]
also i would add that it would be nice to be able to scrap 2d boxes not only 3d ones.

**Comment by milouk** [comment]
@cb109 you CAN specify what to scrape between box/preview/synopsis. Edit the config.json and change `enabled` field to True/False the box/preview/synopsis key

@Giuleus957 you CAN also scrape box-2d by editting the config.json file and instead of box-3d change it to box-2d :)

Please report if this was sufficient in order to close the issue
